TYPE=VIEW
query=select `dbrestoran`.`tblorderdetail`.`idorderdetail` AS `idorderdetail`,`dbrestoran`.`tblorderdetail`.`idorder` AS `idorder`,`dbrestoran`.`tblorderdetail`.`idmenu` AS `idmenu`,`dbrestoran`.`tblorderdetail`.`jumlah` AS `jumlah`,`dbrestoran`.`tblorderdetail`.`hargajual` AS `hargajual`,`dbrestoran`.`tblmenu`.`idkategori` AS `idkategori`,`dbrestoran`.`tblmenu`.`menu` AS `menu`,`dbrestoran`.`tblmenu`.`gambar` AS `gambar`,`dbrestoran`.`tblmenu`.`harga` AS `harga`,`dbrestoran`.`tblkategori`.`kategori` AS `kategori`,`dbrestoran`.`tblorder`.`idpelanggan` AS `idpelanggan`,`dbrestoran`.`tblorder`.`tglorder` AS `tglorder`,`dbrestoran`.`tblorder`.`total` AS `total`,`dbrestoran`.`tblorder`.`bayar` AS `bayar`,`dbrestoran`.`tblorder`.`kembali` AS `kembali`,`dbrestoran`.`tblorder`.`status` AS `status`,`dbrestoran`.`tblpelanggan`.`pelanggan` AS `pelanggan`,`dbrestoran`.`tblpelanggan`.`alamat` AS `alamat`,`dbrestoran`.`tblpelanggan`.`telp` AS `telp`,`dbrestoran`.`tblpelanggan`.`email` AS `email`,`dbrestoran`.`tblpelanggan`.`password` AS `password`,`dbrestoran`.`tblpelanggan`.`aktif` AS `aktif` from ((((`dbrestoran`.`tblorderdetail` join `dbrestoran`.`tblorder` on(`dbrestoran`.`tblorderdetail`.`idorder` = `dbrestoran`.`tblorder`.`idorder`)) join `dbrestoran`.`tblpelanggan` on(`dbrestoran`.`tblorder`.`idpelanggan` = `dbrestoran`.`tblpelanggan`.`idpelanggan`)) join `dbrestoran`.`tblmenu` on(`dbrestoran`.`tblorderdetail`.`idmenu` = `dbrestoran`.`tblmenu`.`idmenu`)) join `dbrestoran`.`tblkategori` on(`dbrestoran`.`tblmenu`.`idkategori` = `dbrestoran`.`tblkategori`.`idkategori`))
md5=bb9eef048432bcba9ea0c10db54b9a6b
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-01-28 05:39:10
create-version=2
source=SELECT tblorderdetail.idorderdetail, tblorderdetail.idorder, tblorderdetail.idmenu, tblorderdetail.jumlah, tblorderdetail.hargajual, tblmenu.idkategori, tblmenu.menu, tblmenu.gambar, tblmenu.harga, tblkategori.kategori, tblorder.idpelanggan, tblorder.tglorder, tblorder.total, tblorder.bayar, tblorder.kembali, tblorder.status, tblpelanggan.pelanggan, tblpelanggan.alamat, tblpelanggan.telp, tblpelanggan.email, tblpelanggan.password, tblpelanggan.aktif\nFROM (((tblorderdetail INNER JOIN tblorder ON tblorderdetail.idorder = tblorder.idorder) INNER JOIN tblpelanggan ON tblorder.idpelanggan = tblpelanggan.idpelanggan) INNER JOIN tblmenu ON tblorderdetail.idmenu = tblmenu.idmenu) INNER JOIN tblkategori ON tblmenu.idkategori = tblkategori.idkategori
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `dbrestoran`.`tblorderdetail`.`idorderdetail` AS `idorderdetail`,`dbrestoran`.`tblorderdetail`.`idorder` AS `idorder`,`dbrestoran`.`tblorderdetail`.`idmenu` AS `idmenu`,`dbrestoran`.`tblorderdetail`.`jumlah` AS `jumlah`,`dbrestoran`.`tblorderdetail`.`hargajual` AS `hargajual`,`dbrestoran`.`tblmenu`.`idkategori` AS `idkategori`,`dbrestoran`.`tblmenu`.`menu` AS `menu`,`dbrestoran`.`tblmenu`.`gambar` AS `gambar`,`dbrestoran`.`tblmenu`.`harga` AS `harga`,`dbrestoran`.`tblkategori`.`kategori` AS `kategori`,`dbrestoran`.`tblorder`.`idpelanggan` AS `idpelanggan`,`dbrestoran`.`tblorder`.`tglorder` AS `tglorder`,`dbrestoran`.`tblorder`.`total` AS `total`,`dbrestoran`.`tblorder`.`bayar` AS `bayar`,`dbrestoran`.`tblorder`.`kembali` AS `kembali`,`dbrestoran`.`tblorder`.`status` AS `status`,`dbrestoran`.`tblpelanggan`.`pelanggan` AS `pelanggan`,`dbrestoran`.`tblpelanggan`.`alamat` AS `alamat`,`dbrestoran`.`tblpelanggan`.`telp` AS `telp`,`dbrestoran`.`tblpelanggan`.`email` AS `email`,`dbrestoran`.`tblpelanggan`.`password` AS `password`,`dbrestoran`.`tblpelanggan`.`aktif` AS `aktif` from ((((`dbrestoran`.`tblorderdetail` join `dbrestoran`.`tblorder` on(`dbrestoran`.`tblorderdetail`.`idorder` = `dbrestoran`.`tblorder`.`idorder`)) join `dbrestoran`.`tblpelanggan` on(`dbrestoran`.`tblorder`.`idpelanggan` = `dbrestoran`.`tblpelanggan`.`idpelanggan`)) join `dbrestoran`.`tblmenu` on(`dbrestoran`.`tblorderdetail`.`idmenu` = `dbrestoran`.`tblmenu`.`idmenu`)) join `dbrestoran`.`tblkategori` on(`dbrestoran`.`tblmenu`.`idkategori` = `dbrestoran`.`tblkategori`.`idkategori`))
mariadb-version=100411
